### PR TITLE
Make running app.js cwd agnostic, extend config to allow changing dataDir

### LINKED ISSUE #339: [Bug]: app.js will not run from a different directory than projectRoot
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I was trying to run the app using `node {path/to/actual-server}/app.js` from a different directory because I had a standard template smf manifest set up to run node instances.

The `migrate` module appears to look in the cwd as opposed to project root so it throws the below error in the `src/migrations.js` file.

### What error did you receive?

*Directory structure redacted*

```js
Rejection: [Error: ENOENT: no such file or directory, scandir '{cwd}/migrations'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '{cwd}/migrations'
}
```

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

_No response_

### Operating System

Other

### LINKED ISSUE #340: [Bug]: if /data exists there is no way to specify the dataDir through config
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The directory structure on my host means that I already have a `/data` directory, however it is owned by root. As there is a hard check to always use `/data` as the dataDir if it exists, and dataDir is not configurable, actual-server crashes with EACCES when it tries to write to /data.

### What error did you receive?

```js
Rejection: [Error: EACCES: permission denied, mkdir '/data/server-files'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/data/server-files'
}
```

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

_No response_

### Operating System

Other

### PR DESCRIPTION
**Pull request by matt-fidd**
Fixes #339 and fixes #340

### CODE REVIEW

File: src/load-config.js [hunk 1]
```diff
@@ -33,6 +33,8 @@ if (process.env.ACTUAL_CONFIG_PATH) {
     `loading config from ACTUAL_CONFIG_PATH: '${process.env.ACTUAL_CONFIG_PATH}'`,
   );
   userConfig = parseJSON(process.env.ACTUAL_CONFIG_PATH);
+
+  defaultDataDir = userConfig.dataDir ?? defaultDataDir;
```
Comment (MatissJanis) [inline src/load-config.js:37]: **💬 suggestion:** ‏nice! Could you also add a `debug` line for this new config (in this same file.. scroll down a few lines to find the other `debug` lines).

Comment (matt-fidd) [reply src/load-config.js:37]: Ah, of course! Updated for you now.

**Review by MatissJanis — APPROVED** [review]
Thanks!
